# Generated by Django 4.2.4 on 2023-08-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('studentFirstName', models.CharField(max_length=20)),
                ('studentMiddleName', models.CharField(max_length=20)),
                ('studentLastName', models.CharField(max_length=20)),
                ('studentGender', models.CharField(max_length=6)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentPhoneNumber', models.CharField(max_length=13)),
                ('studentAddress', models.TextField(max_length=100)),
                ('studentStandard', models.IntegerField()),
                ('studentAdmissionDate', models.DateTimeField()),
                ('studentRemarks', models.TextField(max_length=100)),
                ('studentDescipline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherFirstName', models.CharField(max_length=20)),
                ('teacherMiddleName', models.CharField(max_length=20)),
                ('teacherLastName', models.CharField(max_length=20)),
                ('teacherGender', models.CharField(max_length=6)),
                ('teacherEmail', models.EmailField(max_length=254)),
                ('teacherPhoneNumber', models.CharField(max_length=13)),
                ('teacherAddress', models.TextField(max_length=100)),
                ('teacherJoiningDate', models.DateTimeField()),
                ('teacherRemarks', models.TextField(max_length=100)),
                ('teacherDescipline', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStandard',
            fields=[
                ('standardId', models.IntegerField(primary_key=True, serialize=False)),
                ('standardName', models.CharField(max_length=20)),
                ('standardBuildingName', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='akhsAPIs.teacher')),
            ],
        ),
    ]
